### ISSUE TITLE
Self-hosting error when creating an account: relation "users" doesn't exist

### ISSUE THREAD

**Issue by RealPacket** [face-hh/lyntr#17]
When creating an account on a self-hosted lyntr instance (it's local and is for testing my PRs), it throws an error, I followed the instructions in the ReadME for Supabase and MinIO, I don't need reporting (yet), so I didn't follow the reporting instructions, but if I need to, I can do that.
Also, to get it to build, I had to add a key to my .env file called `PUBLIC_CDN_URL`.
I think the instructions are missing something.
Log:
```log
Error fetching user: PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '60',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '107',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
Error fetching user: PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '60',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
```

**Comment by RealPacket** [comment]
@face-hh

**Comment by RealPacket** [comment]
Even after running
```bash
npx drizzle-kit generate
npx drizzle-kit migrate
npx drizzle-kit push
```
(because I forgot some instructions)
it doesn't work.

**Comment by RealPacket** [comment]
> Even after running
> 
> ```shell
> npx drizzle-kit generate
> npx drizzle-kit migrate
> npx drizzle-kit push
> ```
> 
> (because I forgot some instructions) it doesn't work.

The logs after running that and restarting:
```log
Error fetching user: PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '60',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '107',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
Error fetching user: PostgresError: relation "users" does not exist
    at ErrorResponse (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///home/catloaf/Documents/sources/lyntr/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P01',
  position: '60',
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}
```

**Comment by CodeName-Anti** [comment]
you might need to run ``npm install`` before running the drizzle-kit commands

**Comment by GStudiosX2** [comment]
PUBLIC_CDN_URL has nothing to do with databases

**Comment by RealPacket** [comment]
Not sure why the connection is being reset. I'll try to do some stuff and see if it works.
```bash
$ npm install

added 1 package, and audited 512 packages in 2s

95 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
$ npx drizzle-kit generate
npx drizzle-kit migrate
npx drizzle-kit push
drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
6 tables
followers 2 columns 0 indexes 2 fks
history 4 columns 1 indexes 2 fks
likes 3 columns 0 indexes 2 fks
lynts 10 columns 0 indexes 2 fks
notifications 7 columns 0 indexes 3 fks
users 10 columns 0 indexes 0 fks

No schema changes, nothing to migrate 😴
drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
Using 'pg' driver for database querying
[⢿] applying migrations...Error: read ECONNRESET
    at /home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:77696:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PgDialect.migrate (/home/catloaf/Documents/sources/lyntr/node_modules/src/pg-core/dialect.ts:72:3)
    at migrate (/home/catloaf/Documents/sources/lyntr/node_modules/src/node-postgres/migrator.ts:10:2) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
Using 'pg' driver for database querying
[⣯] Pulling schema from database...
Error: read ECONNRESET
    at /home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:77696:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.query (/home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:119635:26)
    at async fromDatabase2 (/home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:21562:25) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by GStudiosX2** [comment]
Did you set the database stuff in the .env ?

**Comment by RealPacket** [comment]
I set:
- DATABASE_URL
- JWT_SECRET

- DB_HOST
- DB_USER
- DB_PASSWORD
- DB_NAME

- PUBLIC_SUPABASE_URL
- PUBLIC_SUPABASE_ANON_KEY

- MINIO_ENDPOINT
- MINIO_ACCESS_KEY
- MINIO_SECRET_KEY
- S3_BUCKET_NAME

**Comment by GStudiosX2** [comment]
> I set:
> - DATABASE_URL
> - JWT_SECRET
> - DB_HOST
> - DB_USER
> - DB_PASSWORD
> - DB_NAME
> - PUBLIC_SUPABASE_URL
> - PUBLIC_SUPABASE_ANON_KEY
> - MINIO_ENDPOINT
> - MINIO_ACCESS_KEY
> - MINIO_SECRET_KEY
> - S3_BUCKET_NAME
> 

Is your database online ?

**Comment by RealPacket** [comment]
![image](https://github.com/user-attachments/assets/85debace-ce3c-429c-8c68-19b119df6ded)

**Comment by RealPacket** [comment]
![image](https://github.com/user-attachments/assets/9ff02384-d03f-4cf7-8473-ac81aecfad60)
My MinIO server on port 9000 is working too

**Comment by RealPacket** [comment]
> Not sure why the connection is being reset. I'll try to do some stuff and see if it works.
> 
> ```shell
> $ npm install
> 
> added 1 package, and audited 512 packages in 2s
> 
> 95 packages are looking for funding
>   run `npm fund` for details
> 
> 1 high severity vulnerability
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> $ npx drizzle-kit generate
> npx drizzle-kit migrate
> npx drizzle-kit push
> drizzle-kit: v0.22.8
> drizzle-orm: v0.31.2
> 
> No config path provided, using default 'drizzle.config.ts'
> Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
> 6 tables
> followers 2 columns 0 indexes 2 fks
> history 4 columns 1 indexes 2 fks
> likes 3 columns 0 indexes 2 fks
> lynts 10 columns 0 indexes 2 fks
> notifications 7 columns 0 indexes 3 fks
> users 10 columns 0 indexes 0 fks
> 
> No schema changes, nothing to migrate 😴
> drizzle-kit: v0.22.8
> drizzle-orm: v0.31.2
> 
> No config path provided, using default path
> Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
> Using 'pg' driver for database querying
> [⢿] applying migrations...Error: read ECONNRESET
>     at /home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:77696:15
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at PgDialect.migrate (/home/catloaf/Documents/sources/lyntr/node_modules/src/pg-core/dialect.ts:72:3)
>     at migrate (/home/catloaf/Documents/sources/lyntr/node_modules/src/node-postgres/migrator.ts:10:2) {
>   errno: -104,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> drizzle-kit: v0.22.8
> drizzle-orm: v0.31.2
> 
> No config path provided, using default path
> Reading config file '/home/catloaf/Documents/sources/lyntr/drizzle.config.ts'
> Using 'pg' driver for database querying
> [⣯] Pulling schema from database...
> Error: read ECONNRESET
>     at /home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:77696:15
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Object.query (/home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:119635:26)
>     at async fromDatabase2 (/home/catloaf/Documents/sources/lyntr/node_modules/drizzle-kit/bin.cjs:21562:25) {
>   errno: -104,
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> ```

I'm going to restart and change VPN servers.

**Comment by RealPacket** [comment]
Bruh, I just turned off the VPN and then it worked. WTF???

**Comment by RealPacket** [comment]
And now there's stuff in my DB. the issues should be solved.
ProtonVPN moment?

**Comment by GStudiosX2** [comment]
> And now there's stuff in my DB. the issues should be solved.
> ProtonVPN moment?

Supabase probably doesn't allow VPN connections

**Comment by RealPacket** [comment]
It works now.

**Comment by RealPacket** [comment]
I suggest that @face-hh update the documentation to say that if you have any problems running the drizzle-kit commands, it might be your ISP or VPN, and reference this issue.

**Comment by RealPacket** [comment]
I opened a PR for that: #18
