### ISSUE TITLE
mate why cant i install the modules... i run npm install and it gives me millions of errors

### ISSUE THREAD

**Issue by chicken-nugget1104** [face-hh/lyntr#60]
mate why cant i install the modules... i run npm install and it gives me millions of errors

**Comment by RealPacket** [comment]
Can you send the error logs here?

**Comment by chicken-nugget1104** [comment]
> Can you send the error logs here?

ok hold

**Comment by chicken-nugget1104** [comment]
im a bit too lazy to make it not have my pc username but...
PS C:\Users\walle\Downloads\lyntr-master\lyntr-master> npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm WARN deprecated gauge@3.0.2: This package is no longer supported.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@discordjs',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@discordjs\rest\node_modules\@discordjs'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@discordjs\\rest\\node_modules\\@discordjs'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@mapbox\node-pre-gyp'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@mapbox\\node-pre-gyp'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-layers'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-layers'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-4.20.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.17.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.20.0 and node@18.17.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.17.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.17.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.4 found at "C:\Users\walle\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.4.33122.133) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\walle\AppData\Local\Programs\Python\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-node\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\walle\\AppData\\Local\\node-gyp\\Cache\\18.17.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\walle\\AppData\\Local\\node-gyp\\Cache\\18.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\walle\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.17.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-node',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-node\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
npm ERR! gyp ERR! cwd C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node
npm ERR! gyp ERR! node -v v18.17.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\lib\napi-v8 --napi_version=9 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\walle\\Downloads\\lyntr-master\\lyntr-master\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node
npm ERR! node-pre-gyp ERR! node -v v18.17.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings

**Comment by chicken-nugget1104** [comment]
> im a bit too lazy to make it not have my pc username but... PS C:\Users\walle\Downloads\lyntr-master\lyntr-master> npm install npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm WARN deprecated npmlog@5.0.1: This package is no longer supported. npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported. npm WARN deprecated gauge@3.0.2: This package is no longer supported. npm WARN cleanup Failed to remove some directories [ npm WARN cleanup [ npm WARN cleanup 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@discordjs', npm WARN cleanup [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@discordjs\rest\node_modules@discordjs'] { npm WARN cleanup errno: -4048, npm WARN cleanup code: 'EPERM', npm WARN cleanup syscall: 'rmdir', npm WARN cleanup path: 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@discordjs\rest\node_modules\@discordjs' npm WARN cleanup } npm WARN cleanup ], npm WARN cleanup [ npm WARN cleanup 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules', npm WARN cleanup [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@mapbox\node-pre-gyp'] { npm WARN cleanup errno: -4048, npm WARN cleanup code: 'EPERM', npm WARN cleanup syscall: 'rmdir', npm WARN cleanup path: 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@mapbox\node-pre-gyp' npm WARN cleanup } npm WARN cleanup ], npm WARN cleanup [ npm WARN cleanup 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow', npm WARN cleanup [Error: EPERM: operation not permitted, rmdir 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-layers'] { npm WARN cleanup errno: -4048, npm WARN cleanup code: 'EPERM', npm WARN cleanup syscall: 'rmdir', npm WARN cleanup path: 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-layers' npm WARN cleanup } npm WARN cleanup ] npm WARN cleanup ] npm ERR! code 1 npm ERR! path C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node npm ERR! command failed npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js npm ERR! CPU-windows-4.20.0.zip npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build npm ERR! node-pre-gyp info it worked if it ends with ok npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9 npm ERR! node-pre-gyp info using node@18.17.1 | win32 | x64 npm ERR! node-pre-gyp info check checked for "C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node" (not found) npm ERR! node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@4.20.0 and node@18.17.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.20.0/CPU-windows-4.20.0.zip npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@9.3.1 npm ERR! gyp info using node@18.17.1 | win32 | x64 npm ERR! gyp info ok npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@9.3.1 npm ERR! gyp info using node@18.17.1 | win32 | x64 npm ERR! gyp info find Python using Python version 3.12.4 found at "C:\Users\walle\AppData\Local\Programs\Python\Python312\python.exe" npm ERR! gyp info find VS using VS2022 (17.4.33122.133) found at: npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community" npm ERR! gyp info find VS run with --verbose for detailed information npm ERR! gyp info spawn C:\Users\walle\AppData\Local\Programs\Python\Python312\python.exe npm ERR! gyp info spawn args [ npm ERR! gyp info spawn args 'C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py', npm ERR! gyp info spawn args 'binding.gyp', npm ERR! gyp info spawn args '-f', npm ERR! gyp info spawn args 'msvs', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\build\config.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args 'C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\addon.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args 'C:\Users\walle\AppData\Local\node-gyp\Cache\18.17.1\include\node\common.gypi', npm ERR! gyp info spawn args '-Dlibrary=shared_library', npm ERR! gyp info spawn args '-Dvisibility=default', npm ERR! gyp info spawn args '-Dnode_root_dir=C:\Users\walle\AppData\Local\node-gyp\Cache\18.17.1', npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp', npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\Users\\walle\\AppData\\Local\\node-gyp\\Cache\\18.17.1\\<(target_arch)\\node.lib', npm ERR! gyp info spawn args '-Dmodule_root_dir=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node', npm ERR! gyp info spawn args '-Dnode_engine=v8', npm ERR! gyp info spawn args '--depth=.', npm ERR! gyp info spawn args '--no-parallel', npm ERR! gyp info spawn args '--generator-output', npm ERR! gyp info spawn args 'C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\build', npm ERR! gyp info spawn args '-Goutput_dir=.' npm ERR! gyp info spawn args ] npm ERR! Traceback (most recent call last): npm ERR! File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in npm ERR! import gyp # noqa: E402 npm ERR! ^^^^^^^^^^ npm ERR! File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp__init__.py", line 9, in npm ERR! import gyp.input npm ERR! File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in npm ERR! from distutils.version import StrictVersion npm ERR! ModuleNotFoundError: No module named 'distutils' npm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1 npm ERR! gyp ERR! stack at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:514:28) npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12) npm ERR! gyp ERR! System Windows_NT 10.0.19045 npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@tensorflow\tfjs-node\lib\napi-v8" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8" npm ERR! gyp ERR! cwd C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node npm ERR! gyp ERR! node -v v18.17.1 npm ERR! gyp ERR! node-gyp -v v9.3.1 npm ERR! gyp ERR! not ok npm ERR! node-pre-gyp ERR! build error npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node\lib\napi-v8 --napi_version=9 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1) npm ERR! node-pre-gyp ERR! stack at ChildProcess. (C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@mapbox\node-pre-gyp\lib\util\compile.js:89:23) npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:514:28) npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1091:16) npm ERR! node-pre-gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:302:5) npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045 npm ERR! node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules\@mapbox\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build" npm ERR! node-pre-gyp ERR! cwd C:\Users\walle\Downloads\lyntr-master\lyntr-master\node_modules@tensorflow\tfjs-node npm ERR! node-pre-gyp ERR! node -v v18.17.1 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9 npm ERR! node-pre-gyp ERR! not ok npm ERR! * Downloading libtensorflow npm ERR! npm ERR! * Building TensorFlow Node.js bindings

here it is @RealPacket

**Comment by RealPacket** [comment]
I tried running installing stuff on the latest commit and it worked.
I wonder if it's just a Windows® problem™ (I use Fedora btw).

**Comment by RealPacket** [comment]
> I tried running installing stuff on the latest commit and it worked. I wonder if it's just a Windows® problem™ (I use Fedora btw). No sudo needed.

Actually, mine is a little bit outdated.

**Comment by RealPacket** [comment]
![image](https://github.com/user-attachments/assets/890ab527-3586-4f9e-85f9-e63f3dc86631)
Now I have to rebase!

**Comment by RealPacket** [comment]
I've rebased. Gonna rm -rf my node_modules and try again.

**Comment by RealPacket** [comment]
It ran fine.
```bash
$ npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.

> lyntr@0.0.1 postinstall
> patch-package

patch-package 8.0.0
Applying patches...
nsfwjs@4.1.0 ✔

added 617 packages, and audited 618 packages in 25s

104 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

**Comment by chicken-nugget1104** [comment]
> It ran fine. (Commit hash that I'm currently on is [817fd78](https://github.com/face-hh/lyntr/commit/817fd78a822ba31a48663212459098385b1ba1a0))
> 
> ```shell
> $ npm i
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
> npm warn deprecated npmlog@5.0.1: This package is no longer supported.
> npm warn deprecated gauge@3.0.2: This package is no longer supported.
> 
> > lyntr@0.0.1 postinstall
> > patch-package
> 
> patch-package 8.0.0
> Applying patches...
> nsfwjs@4.1.0 ✔
> 
> added 617 packages, and audited 618 packages in 25s
> 
> 104 packages are looking for funding
>   run `npm fund` for details
> 
> 1 high severity vulnerability
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> ```

well it isn't working for me but it may be the fact that i havent done anything but download it and ran npm install

**Comment by chicken-nugget1104** [comment]
tho i do believe it could be that im running outdated software maybe? i havent updated npm in a while or much...

**Comment by chicken-nugget1104** [comment]
then again its with tensorflow i believe?
half of the errors mention that @RealPacket

**Comment by chicken-nugget1104** [comment]
[2024-08-06T16_27_23_679Z-debug-0.log](https://github.com/user-attachments/files/16513399/2024-08-06T16_27_23_679Z-debug-0.log)

**Comment by GStudiosX2** [comment]
Try `~npm rebuild @tensorflow/tfjs-node --build-from-source`

**Comment by chicken-nugget1104** [comment]
> Try `npm rebuild @tensorflow/tfjs-node --build-from-source`
> 
> Or https://github.com/tensorflow/tfjs/blob/HEAD/tfjs-node%2FWINDOWS_TROUBLESHOOTING.md

oh it needs PYTHON???
i dont have python and i cant even use it because it installs but then it does nothing!!!!!!!!!!!!!!!

guess i will never be able to compile this

**Comment by chicken-nugget1104** [comment]
> > Try `npm rebuild @tensorflow/tfjs-node --build-from-source`
> > Or https://github.com/tensorflow/tfjs/blob/HEAD/tfjs-node%2FWINDOWS_TROUBLESHOOTING.md
> 
> oh it needs PYTHON??? i dont have python and i cant even use it because it installs but then it does nothing!!!!!!!!!!!!!!!
> 
> guess i will never be able to compile this

unless yall find a replacement then some people (me) wont be able to build this because i do not wanna do this anymore... my storage is also bad enough already as it is so

**Comment by RealPacket** [comment]
> > > Try `npm rebuild @tensorflow/tfjs-node --build-from-source`
> > > Or https://github.com/tensorflow/tfjs/blob/HEAD/tfjs-node%2FWINDOWS_TROUBLESHOOTING.md
> > 
> > 
> > oh it needs PYTHON??? i dont have python and i cant even use it because it installs but then it does nothing!!!!!!!!!!!!!!!
> > guess i will never be able to compile this
> 
> unless yall find a replacement then some people (me) wont be able to build this because i do not wanna do this anymore... my storage is also bad enough already as it is so

POV: too many `node_modules` (they all added up to 100 GB)

**Comment by chicken-nugget1104** [comment]
> > > > Try `npm rebuild @tensorflow/tfjs-node --build-from-source`
> > > > Or https://github.com/tensorflow/tfjs/blob/HEAD/tfjs-node%2FWINDOWS_TROUBLESHOOTING.md
> > > 
> > > 
> > > oh it needs PYTHON??? i dont have python and i cant even use it because it installs but then it does nothing!!!!!!!!!!!!!!!
> > > guess i will never be able to compile this
> > 
> > 
> > unless yall find a replacement then some people (me) wont be able to build this because i do not wanna do this anymore... my storage is also bad enough already as it is so
> 
> POV: too many `node_modules` (they all added up to 100 GB)
:C
![image](https://github.com/user-attachments/assets/b69d4621-b29c-4187-a952-7e63c406d22f)

**Comment by GStudiosX2** [comment]
> > > > Try `npm rebuild @tensorflow/tfjs-node --build-from-source`
> > > > Or https://github.com/tensorflow/tfjs/blob/HEAD/tfjs-node%2FWINDOWS_TROUBLESHOOTING.md
> > > 
> > > 
> > > oh it needs PYTHON??? i dont have python and i cant even use it because it installs but then it does nothing!!!!!!!!!!!!!!!
> > > guess i will never be able to compile this
> > 
> > 
> > unless yall find a replacement then some people (me) wont be able to build this because i do not wanna do this anymore... my storage is also bad enough already as it is so
> 
> POV: too many `node_modules` (they all added up to 100 GB)

How does it add up to 100 GB it's like less than 2 GB

**Comment by RealPacket** [comment]
Me when 1 TB SSD:
![image](https://github.com/user-attachments/assets/2b3114d8-d2fd-487c-9622-1402e09b3dff)

**Comment by face-hh** [comment]
Closing this due to inactivity
